apiVersion: v2
appVersion: v0.9.20
description: Atomix storage plugin for multi-Raft stores
home: https://cloud.atomix.io
keywords:
- atomix
kubeVersion: '>=1.17.0'
maintainers:
- email: adib@opennetworking.org
  name: adib
- email: jordan@opennetworking.org
  name: kuujo
name: atomix-raft-storage
type: application
version: 0.1.26
