apiVersion: v2
appVersion: v1.1.2
dependencies:
- alias: controller
  name: atomix-controller
  repository: file://../atomix-controller
  version: 1.0.0
- alias: runtime-controller
  name: atomix-runtime-controller
  repository: file://../atomix-runtime-controller
  version: 1.7.0
- alias: sidecar-controller
  name: atomix-sidecar-controller
  repository: file://../atomix-sidecar-controller
  version: 1.1.3
- alias: raft-controller
  condition: stores.raft.enabled
  name: atomix-raft-controller
  repository: file://../atomix-raft-controller
  version: 0.7.0
- alias: shared-memory-controller
  condition: stores.shared-memory.enabled
  name: atomix-shared-memory-controller
  repository: file://../atomix-shared-memory-controller
  version: 0.7.0
- alias: pod-memory-controller
  condition: stores.pod-memory.enabled
  name: atomix-pod-memory-controller
  repository: file://../atomix-pod-memory-controller
  version: 0.4.2
- alias: consensus-controller
  condition: stores.consensus.enabled
  name: atomix-consensus-controller
  repository: file://../atomix-consensus-controller
  version: 1.5.1
description: Atomix core controllers and data stores
home: https://atomix.io
keywords:
- atomix
kubeVersion: '>=1.17.0'
maintainers:
- email: jordan.halterman@intel.com
  name: Jordan Halterman
name: atomix
type: application
version: 1.1.2
