apiVersion: v2
appVersion: v1.1.3
description: The sidecar controller provides injection of the Atomix sidecar into
  Kubernetes pods.
home: https://atomix.io
keywords:
- atomix
kubeVersion: '>=1.17.0'
maintainers:
- email: jordan.halterman@intel.com
  name: Jordan Halterman
name: atomix-sidecar-controller
type: application
version: 1.1.3
